cardano_chains:
  - prime:
    chain_id: prime
    network_address: 'localhost:13001'
    network_magic: 142
    start_block_hash:
    start_slot: 0
    start_block_number: 0
    confirmation_block_count: 10
    fee_address:
    bridging_addresses:
      - vector:
        chain_id: vector
        address: addr_test1vq6xsx99frfepnsjuhzac48vl9s2lc9awkvfknkgs89srqqslj660
        fee_address:
    other_addresses_of_interest:
  - vector:
    chain_id: vector
    network_address: localhost:23001
    network_magic: 242
    start_block_hash:
    start_slot: 0
    start_block_number: 0
    confirmation_block_count: 10
    fee_address:
    bridging_addresses:
      - prime:
        chain_id: prime
        address: addr_test1vr076kzqu8ejq22y4e3j0rpck54nlvryd8sjkewjxzsrjgq2lszpw
        fee_address:
    other_addresses_of_interest:

bridging_settings:
  min_fee_for_bridging: 10
  utxo_min_value: 1000000

app_settings:
  dbs_path: ./db/
  logs_path: ./logs/
  max_bridging_claims_to_group: 10
  log_level: 2