// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package skyline_program

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("BRW3yQ88gEtrsRZssGsrQfVVBirDmzAtCF6VBPLF4Jvh")
