---
name: Build and Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

  build:
    needs: check
    steps:
      - name: Build
        run: make build

  lint:
    needs: check
    steps:
      - name: Test
        run: make lint

  unittest:
    needs: check
    on:
      workflow_dispatch:
    steps:
      - name: Unit Tests
        run: make unit-test