---
name: Unit Tests

on:
  workflow_dispatch:

jobs:    
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Unit Tests
        run: make unit-test